const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('jarvisCloud', {
  getState: () => ipcRenderer.invoke('cloud:get-state'),
  pair: (serverUrl, pairingCode) => ipcRenderer.invoke('cloud:pair', { serverUrl, pairingCode }),
  sendMessage: (text) => ipcRenderer.invoke('cloud:send-message', { text }),
  createRemoteCommand: (input) => ipcRenderer.invoke('cloud:create-command', input || {}),
  getRemoteCommand: (commandId) => ipcRenderer.invoke('cloud:get-command', { commandId }),
  approveRemoteCommand: (commandId) => ipcRenderer.invoke('cloud:approve-command', { commandId }),
  rejectRemoteCommand: (commandId) => ipcRenderer.invoke('cloud:reject-command', { commandId }),
  getMissionControl: () => ipcRenderer.invoke('life:mission-control'),
  getLifeBootstrap: () => ipcRenderer.invoke('life:bootstrap'),
  getLifeTimeline: (input) => ipcRenderer.invoke('life:timeline', input || {}),
  createLifeProject: (input) => ipcRenderer.invoke('life:project-create', input || {}),
  updateLifeProject: (projectId, input) => ipcRenderer.invoke('life:project-update', { projectId, input: input || {} }),
  getLifeProjectContext: (projectId) => ipcRenderer.invoke('life:project-context', { projectId }),
  recordLifeFeedback: (eventId, input) => ipcRenderer.invoke('life:feedback', { eventId, ...(input || {}) }),
  confirmLifeProposal: (proposalId, revision) => ipcRenderer.invoke('life:proposal-confirm', { proposalId, revision }),
  dismissLifeProposal: (proposalId, revision) => ipcRenderer.invoke('life:proposal-dismiss', { proposalId, revision }),
  updateLifeCommitment: (commitmentId, revision, status) => ipcRenderer.invoke('life:commitment-update', { commitmentId, revision, status }),
  getLifeReminders: (state) => ipcRenderer.invoke('life:reminders', { state }),
  rescheduleLifeReminder: (reminderId, input) => ipcRenderer.invoke('life:reminder-reschedule', { reminderId, ...(input || {}) }),
  mutateLifeReminder: (reminderId, action, revision) => ipcRenderer.invoke('life:reminder-action', { reminderId, action, revision }),
  setLifeMissionIntent: (action, projectId, input) => ipcRenderer.invoke('life:mission-intent', { action, projectId, ...(input || {}) }),
  getLifeMode: () => ipcRenderer.invoke('life:mode-get'),
  setLifeMode: (input) => ipcRenderer.invoke('life:mode-set', input || {}),
  getLifePreferences: () => ipcRenderer.invoke('life:preferences'),
  setLifePreference: (key, value, revision) => ipcRenderer.invoke('life:preference-set', { key, value, revision }),
  resetLifePreference: (key, revision) => ipcRenderer.invoke('life:preference-reset', { key, revision }),
  deleteLifePreference: (key, revision) => ipcRenderer.invoke('life:preference-delete', { key, revision }),
  getLifePeople: (includeArchived) => ipcRenderer.invoke('life:people', { includeArchived }),
  createLifePerson: (input) => ipcRenderer.invoke('life:person-create', input || {}),
  getLifeRelationships: (personId) => ipcRenderer.invoke('life:relationships', { personId }),
  getLifePersonProjectLinks: (input) => ipcRenderer.invoke('life:person-project-links', input || {}),
  getLifeFamilyGrants: (input) => ipcRenderer.invoke('life:family-grants', input || {}),
  getLifeFamilyShared: () => ipcRenderer.invoke('life:family-shared'),
  createLifeRecoveryPlan: (projectId, sourceContextRevision) => ipcRenderer.invoke('life:recovery-create', { projectId, sourceContextRevision }),
  getLifeRecoveryPlan: (planId) => ipcRenderer.invoke('life:recovery-get', { planId }),
  proposeLifeRecoveryPlan: (planId, revision) => ipcRenderer.invoke('life:recovery-propose', { planId, revision }),
  getLifeSources: () => ipcRenderer.invoke('life:sources'),
  createLifeSource: (input) => ipcRenderer.invoke('life:source-create', input || {}),
  updateLifeSource: (sourceId, input) => ipcRenderer.invoke('life:source-update', { sourceId, ...(input || {}) }),
  syncLifeSource: (sourceId) => ipcRenderer.invoke('life:source-sync', { sourceId }),
  getVisionState: () => ipcRenderer.invoke('vision:get-state'),
  listVisionSources: () => ipcRenderer.invoke('vision:list-sources'),
  startVision: (input) => ipcRenderer.invoke('vision:start', input || {}),
  analyzeVision: (input) => ipcRenderer.invoke('vision:analyze', input || {}),
  classifyVisualIntent: (text) => ipcRenderer.invoke('vision:classify-intent', { text }),
  stopVision: () => ipcRenderer.invoke('vision:stop'),
  setVisionSensitiveConsent: (sourceId, allow) => ipcRenderer.invoke('vision:sensitive-consent', { sourceId, allow }),
  listVisionMemories: () => ipcRenderer.invoke('vision:memory-list'),
  getVisionMemory: (memoryId) => ipcRenderer.invoke('vision:memory-get', { memoryId }),
  updateVisionMemory: (memoryId, patch) => ipcRenderer.invoke('vision:memory-update', { memoryId, patch }),
  deleteVisionMemory: (memoryId) => ipcRenderer.invoke('vision:memory-delete', { memoryId }),
  startVoice: () => ipcRenderer.invoke('cloud-voice:start'),
  stopVoice: () => ipcRenderer.invoke('cloud-voice:stop'),
  getVoiceState: () => ipcRenderer.invoke('cloud-voice:state'),
  onState: (callback) => ipcRenderer.on('cloud:state', (_event, state) => callback(state)),
  onVoiceStatus: (callback) => ipcRenderer.on('cloud:voice-status', (_event, state) => callback(state)),
  onMessage: (callback) => ipcRenderer.on('cloud:message', (_event, message) => callback(message)),
  onCoreMode: (callback) => ipcRenderer.on('jarvis:core-mode', (_event, payload) => callback(payload)),
  onVisionState: (callback) => ipcRenderer.on('vision:state', (_event, payload) => callback(payload)),
  onVisionSensitiveConsentRequired: (callback) => ipcRenderer.on('vision:sensitive-consent-required', (_event, payload) => callback(payload)),
  onOpenLifeOs: (callback) => ipcRenderer.on('life:open', () => callback()),
  onLifeProposal: (callback) => ipcRenderer.on('life:proposal', (_event, proposal) => callback(proposal)),
});
