import { useEffect, useState } from 'react';
import { getConnections, reassignDevice, reassignTelegram } from '../api/client';
import { dateLabel, statusLabels } from '../format';
import type { ConnectionProfile } from '../types';

export function ConnectionsPage({ loader = getConnections, refreshToken = 0 }: { loader?: typeof getConnections; refreshToken?: number }) {
  const [profiles, setProfiles] = useState<ConnectionProfile[] | null>(null);
  const [error, setError] = useState('');
  const [move, setMove] = useState<{ type: 'telegram' | 'device'; id: string; from: string; label: string } | null>(null); const [target, setTarget] = useState(''); const [pairingCode, setPairingCode] = useState('');
  useEffect(() => { let active = true; void loader().then((value) => { if (active) { setProfiles(value); setError(''); } }).catch(() => { if (active) setError('Не удалось загрузить карту подключений'); }); return () => { active = false; }; }, [loader, refreshToken]);
  return <>
    <div className="page-heading"><p>FAMILY / DEVICE MAP</p><h1>Устройства</h1><span>Семейные профили, Telegram и устройства Jarvis без доступа к личному содержимому</span></div>
    {error ? <div className="notice error">{error}</div> : !profiles ? <div className="notice">Загрузка подключений…</div> : profiles.length === 0 ? <div className="notice">Семейные профили ещё не созданы.</div> : <div className="profile-list">{profiles.map((profile) => <section className="profile" key={profile.id}>
      <div className="profile-head"><div className="avatar">{profile.displayName.slice(0, 1).toUpperCase()}</div><div><small>{profile.role === 'owner' ? 'ВЛАДЕЛЕЦ' : 'УЧАСТНИК'}</small><h2>{profile.displayName}</h2></div><span>{profile.devices.filter((device) => device.status === 'online').length} online</span></div>
      <div className="connection-columns">
        <div><h3>Telegram</h3>{profile.telegram.length ? profile.telegram.map((identity) => <div className="connection-row" key={identity.id}><span className="telegram-mark">TG</span><div><b>ID {identity.externalId}</b><small>привязан {dateLabel(identity.connectedAt)}</small></div>{profiles.length > 1 ? <button className="row-action" onClick={() => { setMove({ type: 'telegram', id: identity.id, from: profile.id, label: `Telegram ${identity.externalId}` }); setTarget(''); }}>ПЕРЕНАЗНАЧИТЬ</button> : null}</div>) : <p className="muted">Не привязан</p>}</div>
        <div><h3>Устройства</h3>{profile.devices.length ? profile.devices.map((device) => <div className="connection-row" key={device.id}><span className="device-mark">{device.kind === 'computer' ? 'PC' : device.kind.toUpperCase()}</span><div><b>{device.name}</b><small>{device.kind} · сигнал {dateLabel(device.lastSeenAt)}</small></div><em className={device.status}><i />{statusLabels[device.status]}</em>{profiles.length > 1 && device.status !== 'revoked' ? <button className="row-action" onClick={() => { setMove({ type: 'device', id: device.id, from: profile.id, label: device.name }); setTarget(''); }}>ПЕРЕНАЗНАЧИТЬ</button> : null}</div>) : <p className="muted">Нет устройств</p>}</div>
      </div>
    </section>)}</div>}{move ? <div className="modal-backdrop"><section className="move-dialog"><small>FAMILY CONNECTION / REASSIGN</small><h2>{move.label}</h2><p>{move.type === 'device' ? 'Старый токен устройства будет отозван. После операции введи новый код на этом компьютере.' : 'Новые Telegram-сообщения пойдут в выбранный профиль. Старая история не перемещается.'}</p><label>Целевой профиль<select value={target} onChange={(event) => setTarget(event.target.value)}><option value="">Выбрать…</option>{profiles?.filter((profile) => profile.id !== move.from).map((profile) => <option key={profile.id} value={profile.id}>{profile.displayName}</option>)}</select></label>{pairingCode ? <div className="pairing-code"><small>КОД ПОВТОРНОЙ ПРИВЯЗКИ</small><b>{pairingCode}</b></div> : null}<div><button className="secondary" onClick={() => { setMove(null); setPairingCode(''); }}>Закрыть</button>{!pairingCode ? <button className="danger" disabled={!target} onClick={() => void (async () => { try { if (move.type === 'telegram') await reassignTelegram(move.id, target); else setPairingCode((await reassignDevice(move.id, target)).reassignment.code); if (move.type === 'telegram') { setMove(null); setProfiles(await loader()); } } catch { setError('Переназначение не выполнено'); } })()}>Переназначить</button> : null}</div></section></div> : null}
  </>;
}
