import { useEffect, useRef, useState } from 'react';
import { getServiceLogs, getServices, runServiceAction } from '../api/client';
import { dateLabel, serviceTag, statusLabels } from '../format';
import type { Service } from '../types';

export function ServicesPage({ refreshToken = 0 }: { refreshToken?: number }) {
  const [services, setServices] = useState<Service[] | null>(null); const [selected, setSelected] = useState<Service | null>(null); const [logs, setLogs] = useState<string[]>([]); const [error, setError] = useState('');
  const [confirmAction, setConfirmAction] = useState<'start' | 'stop' | 'restart' | null>(null); const [operationState, setOperationState] = useState('');
  const operationBusy = useRef(false);
  const selection = useRef('');
  useEffect(() => { void getServices().then(setServices).catch(() => setError('Не удалось загрузить сервисы')); }, [refreshToken]);
  const open = async (service: Service) => { selection.current = service.key; setConfirmAction(null); setOperationState(''); setSelected(service); setLogs([]); try { const result = await getServiceLogs(service.key); if (selection.current === service.key) setLogs(result.state === 'succeeded' ? result.logs.length ? result.logs : ['Записей нет'] : ['Логи временно недоступны']); } catch { if (selection.current === service.key) setLogs(['Логи временно недоступны']); } };
  const execute = async () => { if (!selected || !confirmAction || operationBusy.current) return; operationBusy.current = true; const key = selected.key; const action = confirmAction; setConfirmAction(null); setOperationState('выполняется…'); try { const result = await runServiceAction(key, action); if (selection.current === key) setOperationState(result.status === 'succeeded' ? 'операция успешно завершена' : `результат: ${result.status}${result.errorCode ? ` / ${result.errorCode}` : ''}`); } catch { if (selection.current === key) setOperationState('Ответ не получен. Повторная проверка этой команды использует прежний идентификатор.'); } finally { operationBusy.current = false; } };
  return <><div className="page-heading"><p>RUNTIME / SERVICE CATALOG</p><h1>Сервисы</h1><span>Все управляемые и наблюдаемые контуры на VPS</span></div>
    {error ? <div className="notice error">{error}</div> : !services ? <div className="notice">Загрузка…</div> : <div className="service-table">{services.map((service) => <button key={service.key} onClick={() => void open(service)}><span className="tag">{serviceTag(service.key)}</span><b>{service.name}<small>{service.key} · {service.type || 'service'}</small></b><em className={service.state}><i />{statusLabels[service.state] || service.state}</em><time>{dateLabel(service.observedAt)}</time><strong>ОТКРЫТЬ →</strong></button>)}</div>}
    {selected ? <div className="drawer-backdrop" onClick={() => setSelected(null)}><aside className="drawer" onClick={(event) => event.stopPropagation()}><button className="drawer-close" onClick={() => setSelected(null)}>ЗАКРЫТЬ ×</button><p>SERVICE / {selected.key}</p><h2>{selected.name}</h2><div className={`state ${selected.state}`}><i />{statusLabels[selected.state] || selected.state}</div><h3>УПРАВЛЕНИЕ</h3>{selected.capabilities?.length ? <div className="action-row">{selected.capabilities.map((action) => <button key={action} className={action === 'stop' ? 'danger' : 'secondary'} onClick={() => setConfirmAction(action)}>{action.toUpperCase()}</button>)}</div> : <div className="notice quiet">READ ONLY — операции для этого сервиса выключены.</div>}{operationState ? <div className="operation-state">{operationState}</div> : null}<h3>ПОСЛЕДНИЕ ЛОГИ</h3><pre>{logs.length ? logs.join('\n') : 'загрузка…'}</pre></aside>{confirmAction ? <div className="confirm-dialog" onClick={(event) => event.stopPropagation()}><small>ПОДТВЕРЖДЕНИЕ ОПЕРАЦИИ</small><b>{confirmAction.toUpperCase()} / {selected.name}</b><p>Команда будет отправлена Host Agent один раз и записана в журнал операций.</p><div><button className="secondary" onClick={() => setConfirmAction(null)}>Отмена</button><button className={confirmAction === 'stop' ? 'danger' : 'secondary'} onClick={() => void execute()}>Выполнить</button></div></div> : null}</div> : null}</>;
}
